version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "xBlaz3kx"
    reviewers:
      - "xBlaz3kx"

  - package-ecosystem: "docker"
    directory: "/build/package/"
    schedule:
      interval: "weekly"
    assignees:
      - "xBlaz3kx"
    reviewers:
      - "xBlaz3kx"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "xBlaz3kx"
      - "aljazmark"
    reviewers:
      - "xBlaz3kx"
      - "aljazmark"